"""Python client for the E-Mail-Bridge (AI Documents Ingestion) REST API."""

from .client import DEFAULT_TIMEOUT, IngestionClient, RetryConfig
from .exceptions import (
    ApiError,
    AuthenticationError,
    ForbiddenError,
    IngestionClientError,
    InvalidWebhookPayload,
    NotFoundError,
    ServerError,
    TransportError,
)
from .models import (
    BACKLINK_STATUS_VALUES,
    CONSUMER_STATUS_VALUES,
    DOCUMENT_SOURCE_VALUES,
    Attachment,
    AttachmentContent,
    AttachmentSummary,
    Backlink,
    BusinessDocument,
    BusinessDocumentLine,
    BusinessParty,
    BusinessPaymentMeans,
    BusinessPrice,
    BusinessTaxCategory,
    ClassificationEntry,
    ConsumerStatus,
    MessageDetail,
    MessageStageResult,
    MonetaryTotal,
    ParsedDocument,
    StageMetadataInfo,
    StageResultClassification,
    StageResultDocument,
    TaxSubtotal,
)
from .webhook import is_test_mode, parse_webhook_payload, verify_bearer_token

__version__ = "0.2.0"

#: API spec version this release was verified against (spec/business-document-api.yaml).
SPEC_VERSION = "0.13.0"

__all__ = [
    "BACKLINK_STATUS_VALUES",
    "CONSUMER_STATUS_VALUES",
    "DEFAULT_TIMEOUT",
    "DOCUMENT_SOURCE_VALUES",
    "SPEC_VERSION",
    "ApiError",
    "Attachment",
    "AttachmentContent",
    "AttachmentSummary",
    "AuthenticationError",
    "Backlink",
    "BusinessDocument",
    "BusinessDocumentLine",
    "BusinessParty",
    "BusinessPaymentMeans",
    "BusinessPrice",
    "BusinessTaxCategory",
    "ClassificationEntry",
    "ConsumerStatus",
    "ForbiddenError",
    "IngestionClient",
    "IngestionClientError",
    "InvalidWebhookPayload",
    "MessageDetail",
    "MessageStageResult",
    "MonetaryTotal",
    "NotFoundError",
    "ParsedDocument",
    "RetryConfig",
    "ServerError",
    "StageMetadataInfo",
    "StageResultClassification",
    "StageResultDocument",
    "TaxSubtotal",
    "TransportError",
    "is_test_mode",
    "parse_webhook_payload",
    "verify_bearer_token",
]
